-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 10:10:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_tcc` DEFAULT CHARACTER SET utf8 ;
USE `bd_tcc` ;

-- -----------------------------------------------------
-- Table `bd_tcc`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`estado` (
  `idEstado` VARCHAR(2) NOT NULL,
  `nomeEstado` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeFantasia` VARCHAR(45) NULL,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `inscricaoEstadual` VARCHAR(14) NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `estado_idEstado` VARCHAR(2) NOT NULL,
  `ativo` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_cliente_estado1_idx` (`estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `bd_tcc`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `qtdestoque` INT NOT NULL,
  `foto` BLOB NOT NULL,
  `modelo` CHAR(1) NOT NULL,
  `ativo` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `referencia_UNIQUE` (`referencia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `cliente_idCliente` INT NOT NULL,
  `dtVenda` DATETIME NOT NULL,
  `valorVenda` FLOAT NOT NULL,
  `aprovado` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_venda_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `bd_tcc`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`cor` (
  `idcor` INT NOT NULL AUTO_INCREMENT,
  `nomeCor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcor`),
  UNIQUE INDEX `nomeCor_UNIQUE` (`nomeCor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`corProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`corProduto` (
  `cor_idcor` INT NOT NULL,
  `produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`cor_idcor`, `produto_idProduto`),
  INDEX `fk_corProduto_produto1_idx` (`produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_corProduto_cor1`
    FOREIGN KEY (`cor_idcor`)
    REFERENCES `bd_tcc`.`cor` (`idcor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corProduto_produto1`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `bd_tcc`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`tamanho` (
  `idtamanho` INT NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtamanho`),
  UNIQUE INDEX `tamanho_UNIQUE` (`tamanho` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`tamanhoProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`tamanhoProduto` (
  `tamanho_idtamanho` INT NOT NULL,
  `produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`tamanho_idtamanho`, `produto_idProduto`),
  INDEX `fk_tamanhoProduto_produto1_idx` (`produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_tamanhoProduto_tamanho1`
    FOREIGN KEY (`tamanho_idtamanho`)
    REFERENCES `bd_tcc`.`tamanho` (`idtamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tamanhoProduto_produto1`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `bd_tcc`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`ItensVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`ItensVenda` (
  `venda_idVenda` INT NOT NULL,
  `produto_idProduto` INT NOT NULL,
  `qtdProduto` INT NOT NULL,
  `cor_idcor` INT NOT NULL,
  `tamanho_idtamanho` INT NOT NULL,
  PRIMARY KEY (`venda_idVenda`, `produto_idProduto`, `tamanho_idtamanho`, `cor_idcor`),
  INDEX `fk_ItensVenda_produto1_idx` (`produto_idProduto` ASC) VISIBLE,
  INDEX `fk_ItensVenda_cor1_idx` (`cor_idcor` ASC) VISIBLE,
  INDEX `fk_ItensVenda_tamanho1_idx` (`tamanho_idtamanho` ASC) VISIBLE,
  CONSTRAINT `fk_ItensVenda_venda1`
    FOREIGN KEY (`venda_idVenda`)
    REFERENCES `bd_tcc`.`venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensVenda_produto1`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `bd_tcc`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensVenda_cor1`
    FOREIGN KEY (`cor_idcor`)
    REFERENCES `bd_tcc`.`cor` (`idcor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensVenda_tamanho1`
    FOREIGN KEY (`tamanho_idtamanho`)
    REFERENCES `bd_tcc`.`tamanho` (`idtamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tcc`.`empresaFornecedora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tcc`.`empresaFornecedora` (
  `idempresaFornecedora` INT NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `nomeFantasia` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `estado_idEstado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idempresaFornecedora`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_empresaFornecedora_estado1_idx` (`estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_empresaFornecedora_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `bd_tcc`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
